// <auto-generated />
using HotelProj.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProj.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20230801073451_hotel")]
    partial class hotel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProj.Models.Hotel", b =>
                {
                    b.Property<int>("hotel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hotel_id"));

                    b.Property<string>("amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detailed_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("hotel_phone")
                        .HasColumnType("bigint");

                    b.Property<string>("policies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room_types")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whats_nearby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hotel_id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelProj.Models.Rooms", b =>
                {
                    b.Property<int>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("room_id"));

                    b.Property<string>("availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hotel_id")
                        .HasColumnType("int");

                    b.Property<string>("room_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("room_price")
                        .HasColumnType("int");

                    b.Property<string>("room_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("room_id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
